### 1.Define a symmertic 3x3 matric and print the transpose of the symmetric matrix

#### 3x3 symmetric matrix:
**Transpose** of a matrix is an operator which flips a matrix over its diagonal.It switches the row and column indices of the matrix A by producing another matrix.
In linear algebra, a symmetric matrix is a square matrix that is equal to its transpose.$$A \,is \,symmetric \iff A = A^T$$
 
 So,3x3 symmetric matrix means a symmetric matrix is having 3 rows and 3 columns.


In [8]:
import numpy as np

p=np.random.randint(0,10,(3,3))
print(p)
print("")
print(p.T)
print("")
#s=symmetric matrix and s=p@p^T
s=p @ p.T
print(f"The symmetric 3x3 matrix is\n  {s}" )
print("")

#the transpose value of matrix
print(f"The transpose of this matrix is\n {s.T}")


[[8 0 5]
 [0 9 4]
 [1 0 3]]

[[8 0 1]
 [0 9 0]
 [5 4 3]]

The symmetric 3x3 matrix is
  [[89 20 23]
 [20 97 12]
 [23 12 10]]

The transpose of this matrix is
 [[89 20 23]
 [20 97 12]
 [23 12 10]]


### 2.With the 3x3 matrix calculate the
- lower traingular matrix
- upper triangular matrix

#### Lower triangular matrix:
- A square matrix is lower triangular if all its entries above the main diagonal are zero.
- The tril() function is used to get a lower triangle of an array. Return a copy of an array with elements above the k-th diagonal zeroed.

#### Upper triangular matrix:
- A square matrix is upper triangular if all its entries below the main diagonal are zero.
-  The triu() function is used to get a copy of a matrix with the elements below the k-th diagonal zeroed.

In [36]:
x=np.random.randint(0,9,(3,3))
print(f"The 3x3 matrix is\n {x}")
print("")
#lower triangular matrix
print(f"The lower triangular matrix is\n {np.tril(x)}")
print("")
#upper triangular matrix
print(f"The upper triangular matrix is\n {np.triu(x)}")

The 3x3 matrix is
 [[3 2 0]
 [4 6 3]
 [8 3 0]]

The lower triangular matrix is
 [[3 0 0]
 [4 6 0]
 [8 3 0]]

The upper triangular matrix is
 [[3 2 0]
 [0 6 3]
 [0 0 0]]


### 3.Define a 5x3 matrix and get the :
- diagonal vector
- get diagonal matrix form vector

#### Diagonal matrix:
- A matrix is diagonal if all elements above and below the main diagonal are zero. Any number of the elements on the main diagonal can also be zero.

- The formula used to get diagonal matrix :**numpy.diag(v, k=0)**,where v=2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal,k=The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

In [3]:
a=np.arange(1,16).reshape(5,3)
print(f"The matrix is\n {a}")
print("")
#diagonal vector
x=np.diagonal(a)
print(f"The diagonal vector is {x}")
print("")
#create a matrix from diagonal vector
y=np.diag(x)
print(f"The matrix is\n {y}")



The matrix is
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

The diagonal vector is [1 5 9]

The matrix is
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


### 4.create a Identiy matrix

#### Identity matrix:
In linear algebra, the identity matrix of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.

In [38]:
print(f"The 3x3 identity matrix is\n  {np.identity(3,dtype='i')}")

The 3x3 identity matrix is
  [[1 0 0]
 [0 1 0]
 [0 0 1]]


### 5. Define a orthogonal matrix and get:
- inverse of matrix

- show that  Q.QT=I 

where Q is the orthogonal matrix

#### Orthogonal matrix:
In linear algebra, an orthogonal matrix, or orthonormal matrix, is a real square matrix whose columns and rows are orthonormal vectors.

One way to express this is

${\displaystyle Q^{\mathrm {T} }Q=QQ^{\mathrm {T} }=I,}Q^{\mathrm {T} }Q=QQ^{\mathrm {T} }=I$,
where QT is the transpose of Q and I is the identity matrix.

This leads to the equivalent characterization: a matrix Q is orthogonal if its transpose is equal to its inverse:

${\displaystyle Q^{\mathrm {T} }=Q^{-1},}$
where Q−1 is the inverse of Q

In [39]:
#random orthogonal matrix
from scipy.stats import ortho_group
import numpy as np
m=ortho_group.rvs(dim=3)
print(f"The orthogonal matrix is\n {m}")
print("")
print(f"The inverse of matrix m is\n {np.linalg.inv(m)}")
print("")
print(f"the transpose of matrix m is\n){np.transpose(m)}")
print("")
#show the condition Q.QT=I,where Q is the orthogonal matrix and I is symmetric matrix
I=np.matmul(m,m.T)
print(f"The symmetric matrix I is\n {I}")


The orthogonal matrix is
 [[-0.9392188  -0.28771706 -0.18731507]
 [ 0.34231968 -0.82641834 -0.44704582]
 [-0.0261779  -0.48399548  0.87467885]]

The inverse of matrix m is
 [[-0.9392188   0.34231968 -0.0261779 ]
 [-0.28771706 -0.82641834 -0.48399548]
 [-0.18731507 -0.44704582  0.87467885]]

the transpose of matrix m is
)[[-0.9392188   0.34231968 -0.0261779 ]
 [-0.28771706 -0.82641834 -0.48399548]
 [-0.18731507 -0.44704582  0.87467885]]

The symmetric matrix I is
 [[1.00000000e+00 2.77555756e-17 1.11022302e-16]
 [2.77555756e-17 1.00000000e+00 3.88578059e-16]
 [1.11022302e-16 3.88578059e-16 1.00000000e+00]]


### 6.Define a matrix and calulate the trace of matrix

#### Trace of matrix:
- Trace of the matrix is defined as the sum along diagonals of the matrix.
- numpy.trace() is used to calculate trace of matrix.

In [40]:
a=np.arange(25).reshape(5,5)
print(f"The matrix is\n {a}")
#calculate the trace of matrix
print("")
print(f"Trace of the matrix is\n {a.trace()}")

The matrix is
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Trace of the matrix is
 60


### 7.define a 3x3 matrix and calc determinant, ie not invertable

In [41]:
a=np.random.randint(1,9,(3,3))
print(a)
np.linalg.det(a)


[[6 7 8]
 [3 6 5]
 [4 3 8]]


50.000000000000014

### 8.create a 2x2 matrix , 1x3 matrix and calculate the rank of the matrix

In [42]:
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,6,(1,3))
print(f"The  2x2 matrix is\n {a}")
print("")
print(f"The  1x3 matrix is\n {b}")
#rank of the matrix
print("")
print(f"The rank of  2x2 matrix is: {np.linalg.matrix_rank(a)}")
print(f"The rank of 1x3 matrix is: {np.linalg.matrix_rank(b)}")

The  2x2 matrix is
 [[9 5]
 [7 4]]

The  1x3 matrix is
 [[0 4 0]]

The rank of  2x2 matrix is: 2
The rank of 1x3 matrix is: 1


### 9.create a 3*6 matrix with zeros and ones and count the zeros in matrix
- also find the size of matrix
- calculate the matrix sparsity: count of zeros/size of matrix

In [43]:
#create a 3*6 matrix with zeros and ones
a=np.random.randint(0,2,(3,6))
print(a)
print("")

#sixe of matrix
print(f"The size of matrix is: {np.size(a)}")

#calculate the matrix sparsity:count of zeros/sixe of matrix
sparcity=1-np.count_nonzero(a)/np.size(a)
print(f"Sparsity of matrix is {sparcity}")

[[0 1 0 1 0 0]
 [0 1 1 0 1 1]
 [0 1 0 0 1 1]]

The size of matrix is: 18
Sparsity of matrix is 0.5


### 10.convert the sparse using csr method and again reconstruct to dense
A = array([ [1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0] ]) #dense matrix

**A dense matrix** stored in a Numpy array can be converted into a sparse matrix using the CSR  representation by calling the csr_matrix() function.

In [44]:
from numpy import array
from scipy.sparse import csr_matrix

# create dense matrix
A = array([[1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0]])
print(A)
print("")

# convert to sparse matrix (CSR method)
sp = csr_matrix(A)
print(sp)
print("")

# reconstruction of dense matrix
B = sp.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


### 11.define a tensor of matrix of shape (3,3,3)

#### Tensor:
- An array of numbers arranged on a regular grid with a variable number of axes is known as a tensor.
- A vector is a one-dimensional or first order tensor and a matrix is a two-dimensional or second order tensor.

In [45]:
# create a tensor of matrix of shape(3*3*3)
tensor=np.random.randint(1,28,(3,3,3))
print(tensor)
print("")

#checking the shape
print(tensor.shape)

[[[12  4  4]
  [14  7 24]
  [25  6 26]]

 [[ 1 11  9]
  [18 22 25]
  [ 9 25 26]]

 [[12 23 15]
  [ 6 12  3]
  [11 15 18]]]

(3, 3, 3)


### 12.create a 2 tensor of size (3,3,3) and perform:
- tensor additon
- tensor substraction

In [46]:
a=np.arange(1,28).reshape(3,3,3)
b=np.arange(1,28).reshape(3,3,3)
print(f"The first tensor is\n {a}")
print("")
print(f"The second tensor is\n {b}")
print("")

#tensor addition
c = a + b
print(f"The result of addition of two tensors is\n {c}")
print("")

#tensor substraction
d = a - b
print(f"The result of substraction of two tensors is\n {d}")


The first tensor is
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

The second tensor is
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

The result of addition of two tensors is
 [[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]

The result of substraction of two tensors is
 [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


### 13.perform a Hadamard Product for the above tensor

#### Hadamard Product:
The element-wise multiplication of one tensor from another tensor with the same dimensions results in a new tensor with the same dimensions is known as Hadamad product.

In [47]:
a=np.arange(1,28).reshape(3,3,3)
b=np.arange(1,28).reshape(3,3,3)
print(f"The first tensor is\n {a}")
print("")
print(f"The second tensor is\n {b}")
print("")

#Hadamard Product:
h = a * b
print(f"The product of two tensors is\n {h}")

The first tensor is
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

The second tensor is
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

The product of two tensors is
 [[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]

 [[361 400 441]
  [484 529 576]
  [625 676 729]]]


### 14.Perform a Tensor division for a tensor of shape T1 and T2 of shape(4,3,3)

In [52]:
T1=np.arange(1,37).reshape(4,3,3)
T2=np.arange(1,37).reshape(4,3,3)
print(f"The first tensor is\n {T1}")
print("")
print(f"The second tensor is\n {T2}")
print("")

# tensor division
d = T1 / T2
print(f"The divided value of two tensors is\n {d}")

The first tensor is
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]

The second tensor is
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]

The divided value of two tensors is
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### 15.define a 2 tensor of 2x2 and calculate the tensor product

- The **tensor product** can be implemented in Numpy using the **tensordot()** function.
- The function takes as arguments the two tensors to be multiplied and the axis on which to sum the products over, called the sum reduction.
- To calculate the tensor product, also called the tensor dot product in NumPy, the axis must be set to 0.

In [7]:
from numpy import array
from numpy import tensordot

A = array([[1,2],[3,4]])
print(f"First tensor\n {A}")
print("")

B = array([[1,2],[3,4]])
print(f"Second tensor\n {B}")
print("")

C = tensordot(A, B, axes=0)
print(f"Tensor product is\n {C}")


First tensor
 [[1 2]
 [3 4]]

Second tensor
 [[1 2]
 [3 4]]

Tensor product is
 [[[[ 1  2]
   [ 3  4]]

  [[ 2  4]
   [ 6  8]]]


 [[[ 3  6]
   [ 9 12]]

  [[ 4  8]
   [12 16]]]]


### 16.calulate the factorization factors a matrix(Lu) decompostion for an array of shape 3x3
- recostruct the original matrix from the decompostion

#### Matrix Decomposition:
- A matrix decomposition is a way of reducing a matrix into its constituent parts.
- A common analogy for matrix decomposition is the factoring of numbers, such as the factoring of 10 into 2 x 5. For this reason, matrix decomposition is also called matrix factorization. 

#### LU Matrix Decomposition:
- The LU decomposition is for square matrices and decomposes a matrix into L and U components.
- The LU decomposition can be implemented in Python with the lu() function.
- The limitation of LU Matrix Decomposition is yhat,it is only implemented on square matrices.

In [51]:
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix is\n {A}")
print("")

# LU decomposition
P, L, U = lu(A)

# P= matrix specifies a way to permute the result or return the result to the original order
print(f"P =\n {P}")
print("")

#L=lower triangular matrix
print(f"L =\n {L}")
print("")

#U=upper triangular matrix
print(f"U =\n {U}")
print("")

# reconstruction of original matrix
B = P.dot(L).dot(U)
print(f"The original matrix is\n {B}")

Matrix is
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

P =
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L =
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

U =
 [[7.00000000e+00 8.00000000e+00 9.00000000e+00]
 [0.00000000e+00 8.57142857e-01 1.71428571e+00]
 [0.00000000e+00 0.00000000e+00 1.11022302e-16]]

The original matrix is
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### 17.from a matrix of shape 3x2
- calculate the QR decompostion
- reconstruct the original matrix

#### QR Decomposition:
- The QR decomposition is for m x n matrices (not limited to square matrices) and decomposes a matrix into Q and R components.
- A = QR ,where A is the matrix that we wish to decompose, Q a matrix with the size m x m, and R is an upper triangle matrix with the size m x n.
- The QR decomposition can be implemented in NumPy using the **qr() function**.

In [8]:
from numpy import array
from numpy.linalg import qr

# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(f"Matrix is\n {A}")

# QR decomposition
Q, R = qr(A, 'complete')

#Q=square matrix
print(f"Q =\n {Q}")
print("")

#R=upper triangular matrix
print(f"R =\n {R}")
print("")

# reconstruction of original matrix
B = Q.dot(R)
print(f"The original matrix is\n {B}")

Matrix is
 [[1 2]
 [3 4]
 [5 6]]
Q =
 [[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]

R =
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

The original matrix is
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


### 18.define a 3x3 matrix calculate:
- cholesky decomposition using lower factorize
- reconstruct the original matrix

#### Cholesky Decomposition:
- The Cholesky decomposition is for square symmetric matrices where all eigenvalues are greater than zero, so-called positive definite matrices
- A = (U^T . U) where , U is the lower triangular matrix and U^T is the transpose of U.
- The Cholesky decomposition can be implemented in NumPy by calling the cholesky() function. 

In [56]:
from numpy import array
from numpy.linalg import cholesky

# define a 3x3 matrix
A = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(f"Matrix is\n {A}")
print("")

# Cholesky decomposition
L = cholesky(A)
print(f"L = {L}")
print("")

# reconstruction of original matrix
B = L.dot(L.T)
print(f"The original matrix is\n {B}")

Matrix is
 [[2 1 1]
 [1 2 1]
 [1 1 2]]

L = [[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]

The original matrix is
 [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


### 19.define a 3x3 matrix and calculate the:
- eigendecomposition

#### Eigen Decomposition:
- The eigendecomposition decomposes a square matrix into a set of eigenvectors and eigenvalues.
- The eigendecomposition can be calculated in NumPy using the **eig() function**.

In [60]:
# Eigen-decomposition
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix is\n {A}")
print("")

# calculate Eigendecomposition
values, vectors = eig(A)

#values=eigenvalues
print(f"eigen values={values}")
print("")

#vectors=eigen vectors
print(f"eigen vectors={vectors}")

Matrix is
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

eigen values=[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

eigen vectors=[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### 20.from the above eigendecomposition confirm an eigenvector and eigenvalue

#### The eigenvectors are returned as a matrix with the same dimensions as the parent matrix, where each column is an eigenvector, e.g. the first eigenvector is vectors[:, 0]. Eigenvalues are returned as a list, where value indices in the returned array are paired with eigenvectors by column index, e.g. the first eigenvalue at values[0] is paired with the first eigenvector at vectors[:, 0].

In [11]:
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# calculate eigendecomposition
values, vectors = eig(A)

# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
print("")
C = vectors[:, 0] * values[0]
print(C)
#Av=(lambda)v should be proved

[ -3.73863537  -8.46653421 -13.19443305]

[ -3.73863537  -8.46653421 -13.19443305]


### 21.Reconstruct the matrix from the Eigendecompostion

#### We can reverse the process and reconstruct the original matrix given only the eigenvectors and eigenvalues.

- First, the list of eigenvectors must be converted into a matrix, where each vector becomes a row. 
- The eigenvalues need to be arranged into a diagonal matrix. The NumPy diag() function can be used for this.
- we need to calculate the inverse of the eigenvector matrix, which we can achieve with the inv() NumPy function.
- Finally, these elements need to be multiplied together with the dot() function.



In [61]:
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print("")

# calculate eigenvectors and eigenvalues
values, vectors = eig(A)

# create matrix from eigenvectors
Q = vectors

# create inverse of eigenvectors matrix
R = inv(Q)

# create diagonal matrix from eigenvalues
L = diag(values)

# reconstruction of the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### 22.calculate the L1 norm for a 1x3 matrix

#### Vector Norm:
- The length of the vector is referred to as the vector norm or the vector’s magnitude.
- The length of a vector is a nonnegative number that describes the extent of the vector in space.

#### L1 Norm:
- The length of a vector can be calculated using the L1 norm, where the 1 is a superscript of the L, i.e. L^1.
-  This length is sometimes called the taxicab norm or the Manhattan norm.
- The L1 norm of a vector can be calculated in NumPy using the norm() function with a parameter to specify the norm order, in this case 1.

In [14]:
# l1 norm of a vector
from numpy import array
from numpy.linalg import norm

a = array([1, 2, 3])
print(a)
print("")

l1 = norm(a, 1)
print(l1)

[1 2 3]

6.0


### 23.calculate the L2 norm for the 1x4 matrix

#### L2 Norm:
- The length of a vector can be calculated using the L2 norm, where the 2 is a superscript of the L, e.g. L^2.
- It is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin. The result is a positive distance value.
- The L2 norm of a vector can be calculated in NumPy using the norm() function with default parameters.

In [63]:
from numpy import array
from numpy.linalg import norm

#create 1*4 matrix
a = array([1, 2, 3,4])
print(a)
print("")

#calculation of L2 Norm
l2 = norm(a)
print(l2)

[1 2 3 4]

5.477225575051661
